### ISSUE TITLE
xwayland applications crash in swc

### ISSUE THREAD

**Issue by paulhandy** [michaelforney/swc#14]
using xorg-server-xwayland version 1.16.0-5 on arch linux. Here is an example attempting to open st. Each X application attempted ends with a similar error log.

> > > XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":6"
> > >       after 595 requests (362 known processed) with 0 events remaining.

Note: when running `swc-launch -- velox`, X applications crash the whole server before an error message ensues. when running `swc-launch -- swc/example/wm`, the quoted message is given.

**Comment by Drakulix** [comment]
Is there any update on this? I am running the latest (git) velox and swc versions on Arch Linux with (an unpatched) Xwayland 1.16.3 and no Xwayland applications are shown. They run endlessly (I've waited about 5 minutes) without any error, Xwayland is running as well, but they do not show up. swc-launch is also not logging anything interesting.

**Comment by michaelforney** [comment]
Are you certain that DISPLAY is set correctly (to the Xwayland instance)? If you run from a screen/tmux session they may be showing up in your X11 session.

**Comment by Drakulix** [comment]
I am running velox from my main desktop using 'swc-launch -t /dev/tty2 -- velox' and launch the applications through an st-wl terminal, not via screen or tmux.
'echo $DISPLAY' prints :1 in the st-wl terminal and not :0 like on my main desktop.
'pgrep Xwayland' also tells me, that Xwayland is running.

**Comment by Drakulix** [comment]
No idea, how I could debug that?

**Comment by michaelforney** [comment]
Can you provide some xwayland logs running with WAYLAND_DEBUG=client?

**Comment by michaelforney** [comment]
Xwayland support has been removed.
