### ISSUE TITLE
Could not become DRM master

### ISSUE THREAD

**Issue by tjaartvdwalt** [michaelforney/swc#16]
Hi,

I am new to swc. When I try to run the example wm I get an error:
I run the command:
````
 swc-launch example/wm
````
 The error is:
````
[swc:libswc/drm.c:186] DEBUG: /dev/dri/card0 is the primary GPU
Could not become DRM master: Invalid argument
[swc:libswc/drm.c:313] ERROR: Could not open DRM device at /dev/dri/card0
[swc:libswc/swc.c:118] ERROR: Could not initialize DRM
Server exited with status 1
Restoring VT to original state
````
After some digging it seems the error comes from the sendmsg()  call in launch/protocol.c (line 40) returning the "Invalid argument" error code. I am not sure if I am doing something wrong here.

**Comment by actionless** [comment]
have the same problem.

```sh
$ lspci | grep -i nvidia
01:00.0 VGA compatible controller: NVIDIA Corporation G98M [Quadro NVS 160M] (rev a1)
$ glxinfo | grep rendering
direct rendering: Yes
$ ll -R (which swc-launch)
-rwsr-xr-x 1 root root 19K Jan  9 01:20 /usr/sbin/swc-launch*
```

**Comment by rr-** [comment]
I just asked related question on [SO](http://stackoverflow.com/questions/29708596/drmdropmaster-requires-root-privileges).

**Comment by tjaartvdwalt** [comment]
I am closing this issue.

I ended up writing Weston plugin instead of using swc.
