### ISSUE TITLE
xwayland: keyboard gets jammed for some programs

### ISSUE THREAD

**Issue by krobelus** [michaelforney/swc#18]
I can reproduce this when opening a long pdf file with zathura and then pressing and holding j to scroll down. After some time (usually 5 to 10 seconds for me (using xset r rate 200 50)) the scrolling stops for a short amount of time.
If I release the key shortly after the scrolling stops then the key events are apparently delayed by one for some time (so when I press a key, the previously pressed key is noticed).
This does not seem to happen for some other X applications such as xterm, emacs or firefox
but it does for some others as well.

**Comment by michaelforney** [comment]
Xwayland support has been removed.
