### ISSUE TITLE
x11 backend

### ISSUE THREAD

**Issue by acrisci** [michaelforney/swc#19]
While developing a window manager with swc, it would be nice to have the session render to an X window as part of my development environment.

The desired behavior would be the same as when I type `weston` into my terminal in X.

**Comment by acrisci** [comment]
I'm available to work on this. Do you have a preferred implementation in mind? I was going to look and see how weston does it and see if a similar approach would work.

**Comment by SirCmpwn** [comment]
:+1:

**Comment by bqv** [comment]
close
