### ISSUE TITLE
Path in makefile not /usr/local

### ISSUE THREAD

**Issue by sir-murray** [michaelforney/swc#26]
Not entirely sure if I'm missing something here, but should the default path prefix in the Makefile not be 
```
PREFIX          ?= /usr/local
```
Instead of:
```
PREFIX          ?= /usr
```

**Comment by pickfire** [comment]
I seem to have some error similar to this, when I do `make -j4`:
```
Makefile:69: *** Could not find package wld.  Stop.
```

**Comment by sir-murray** [comment]
That is probably unrelated, do you have wld installed?
https://github.com/michaelforney/wld

**Comment by pickfire** [comment]
Yeah, I did have `wld` installed by:
```
make -j4
sudo make install -j4
```
And I only modify the **DRM_BACKEND** part in `config.mk`.

**Comment by sir-murray** [comment]
Can your pkg-config find wld?
If not, run
```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
```
and try again.

**Comment by pickfire** [comment]
Thanks a lot. It works after I ran:
```fish
set -U PKG_CONFIG_PATH '/usr/local/lib/pkgconfig`
make -j4
```
