### ISSUE TITLE
Crashes when switching between x11 and swc based wms.

### ISSUE THREAD

**Issue by johan-bjareholt** [michaelforney/swc#28]
Maybe not a top priority bug, but worth mentioning.

If you run x11 in one VT and a swc based wm in the other (have tried both velox and my own zentwm), swc will crash when switching back.

Simply switching between a empty VT and a VT with a swc wm is fine though.

You don't need to run any xapplications in the swc wm, it will crash even if there's solely wayland applications running (tried with st-wl). Someitmes it will even crash if there's no applications running, but sometimes it works.

https://github.com/johan-bjareholt/zentwm/issues/2

Does this work for anyone else, or does it only crash for me?

**Comment by michaelforney** [comment]
Can you give me a backtrace?

**Comment by johan-bjareholt** [comment]
This is very strange.

When i recreate the bug without gdb, it crashes properly.
When i run it in gdb however it freezes with 100% cpu usage so it doesn't even crash. I have tried messing around with multiple gdb options for over 30min now with no success. Here are some methods i tried.

- swc-launch -- gdb --batch -ex "bt full" -ex "set logging on" -ex run ./velox -ex "quit"
- swc-launch -- gdb --batch -ex "set logging on" -ex run ./velox -ex backtrace -ex "quit"
- swc-launch -- gdb --batch -ex run ./velox
- first "swc-launch ./velox", then "gdb attach $PID"

All these result in the same manner, the velox process gets stuck at 100% cpu usage.

I have absolutely no idea why it reacts like this, don't how to work around this behavior.

**Comment by michaelforney** [comment]
Maybe try valgrind?

**Comment by johan-bjareholt** [comment]
Thanks for the tip, never thought about using valgrind to backtrace, but i guess that works too.

> ==2745== Memcheck, a memory error detector
==2745== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==2745== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==2745== Command: ./velox
==2745== 
==2745== Syscall param sendmsg(msg.msg_iov[0]) points to uninitialised byte(s)
==2745==    at 0x589A330: __sendmsg_nocancel (in /usr/lib/libc-2.21.so)
==2745==    by 0x5063780: ??? (in /usr/lib/libwayland-server.so.0.1.0)
==2745==    by 0x506192E: wl_display_flush_clients (in /usr/lib/libwayland-server.so.0.1.0)
==2745==    by 0x5061987: wl_display_run (in /usr/lib/libwayland-server.so.0.1.0)
==2745==    by 0x40514C: main (velox.c:348)
==2745==  Address 0xa31121e is 4,126 bytes inside a block of size 16,424 alloc'd
==2745==    at 0x4C29F90: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2745==    by 0x50638B1: ??? (in /usr/lib/libwayland-server.so.0.1.0)
==2745==    by 0x5061D12: wl_client_create (in /usr/lib/libwayland-server.so.0.1.0)
==2745==    by 0x4E4C2BE: ??? (in /usr/lib/libswc.so.0.0)
==2745==    by 0x4E48D8F: swc_initialize (in /usr/lib/libswc.so.0.0)
==2745==    by 0x40510C: main (velox.c:340)
==2745== 
==2745== Syscall param ioctl(generic) points to uninitialised byte(s)
==2745==    at 0x5891B27: ioctl (in /usr/lib/libc-2.21.so)
==2745==    by 0x5B57E47: drmIoctl (in /usr/lib/libdrm.so.2.4.0)
==2745==    by 0x5B5AF70: drmPrimeFDToHandle (in /usr/lib/libdrm.so.2.4.0)
==2745==    by 0x72B3775: drm_intel_bo_gem_create_from_prime (in /usr/lib/libdrm_intel.so.1.0.0)
==2745==    by 0x601A0A7: ??? (in /usr/lib/libwld.so.0.0)
==2745==    by 0x6018900: wld_import_buffer (in /usr/lib/libwld.so.0.0)
==2745==    by 0x4E409B7: ??? (in /usr/lib/libswc.so.0.0)
==2745==    by 0x6C821EF: ffi_call_unix64 (in /usr/lib/libffi.so.6.0.4)
==2745==    by 0x6C81C57: ffi_call (in /usr/lib/libffi.so.6.0.4)
==2745==    by 0x5064FF9: ??? (in /usr/lib/libwayland-server.so.0.1.0)
==2745==    by 0x5061435: ??? (in /usr/lib/libwayland-server.so.0.1.0)
==2745==    by 0x5063231: wl_event_loop_dispatch (in /usr/lib/libwayland-server.so.0.1.0)
==2745==  Address 0xffefffa60 is on thread 1's stack
==2745==  in frame #2, created by drmPrimeFDToHandle (???)
==2745== 
==2745== 
==2745== HEAP SUMMARY:
==2745==     in use at exit: 804,557 bytes in 2,316 blocks
==2745==   total heap usage: 16,917 allocs, 14,601 frees, 2,529,327 bytes allocated
==2745== 
==2745== LEAK SUMMARY:
==2745==    definitely lost: 184 bytes in 2 blocks
==2745==    indirectly lost: 0 bytes in 0 blocks
==2745==      possibly lost: 21,632 bytes in 48 blocks
==2745==    still reachable: 782,741 bytes in 2,266 blocks
==2745==         suppressed: 0 bytes in 0 blocks
==2745== Rerun with --leak-check=full to see details of leaked memory
==2745== 
==2745== For counts of detected and suppressed errors, rerun with: -v
==2745== Use --track-origins=yes to see where uninitialised values come from
==2745== ERROR SUMMARY: 6 errors from 2 contexts (suppressed: 0 from 0)

**Comment by michaelforney** [comment]
It doesn't seem like swc is crashing to me:

    FATAL: Failed to set DRM master: Invalid argument

**Comment by johan-bjareholt** [comment]
That's seems to be correct. After googling around i see that others have had similar issues but with X11 under the intel driver. Since it seems like i'm the only one experiencing this, it's not really anything critical and seems to be a bug related to intel i915 DRM graphics drivers only i'll just close this issue.
