### ISSUE TITLE
failing to swc-launch example/wm, velox

### ISSUE THREAD

**Issue by gertjanvanzwieten** [michaelforney/swc#34]
In an attempt to try out velox I'm running into a pretty basic problem with swc: I cannot seem to get it to work.

My system is an Acer Aspire with Intel HD graphics, running debian testing with kernel 4.5 and the i915 module loaded. Weston runs without any problems. I built and installed wld, swc, and velox local to my home directory and try to start velox as:

    swc-launch velox

This fails as follows

    Running on /dev/tty1
    [swc:libswc/drm.c:149] DEBUG: /dev/dri/card0 is the primary GPU
    # find_driver: Trying DRM driver `intel'
    [swc:libswc/drm.c:296] ERROR: Could not create WLD DRM renderer
    [swc:libswc/swc.c:128] ERROR: Could not initialize DRM
    Server exited with status 1
    Restoring VT to original state

The swc-launch executable is setuid and owned by root. Removing the setuid bit yields the same result. Fully switching user to root also yields the same result. The same holds for both velox and example/wm. Interestingly, for all of these three options, swc-launch weston does work.

Note that this issue is similar to #16, which appears unresolved.

Any suggestions as to what I could be doing wrong, or what steps to take to debug this issue are highly welcomed.

**Comment by michaelforney** [comment]
Sounds like wld failed to initialize.

You might have a different generation of intel graphics that is not yet supported by wld. You could try with WLD_DRM_DUMB=1 which will use driver-generic buffers and software rendering.

**Comment by gertjanvanzwieten** [comment]
That helped, thanks!
