### ISSUE TITLE
can't launch swc using nvidia binary

### ISSUE THREAD

**Issue by cellsheet** [michaelforney/swc#37]
Hello, I have a pascal based GTX 1080 on my arch setup  using the proprietary NVIDIA binary driver (nouveau won't get firmwares for a long time). when I run `swc-launch example`, the output tells me it's running on /dev/tty<x>, but there is nothing there. `swc-launch velox` replies:

```
running on /dev/tty2
[swc:libswc/drm.c:149] DEBUG: /dev/dri/card0 is the primary GPU
# find_driver: Trying DRM driver `intel'
# find_driver: Trying DRM driver `nouveau'
[swc:libswc/drm.c:291] ERROR: Could not create WLD DRM context
[swc:libswc/swc.c:128] ERROR: Could not initialize DRM
```

Is this due to the lack of support for this driver? If so, where would a good way to learn about how to implement this would be at so I may learn to help contribute one day to something like this (if this is the issue at hand). I'm trying to get into wayland, but I'm not too familiar with it right now.

EDIT: NVidia binaries do not support wayland, just learned about this. Sorry.

**Comment by DmitryHetman** [comment]
No, nvidia supports wayland, Velox and other compositrors doesn't support EGLstreams

**Comment by shawn-peng** [comment]
maybe the reason is that you are using nouveau driver? I would suggest try the Nvidia's closed source driver.
