### ISSUE TITLE
Firefox (and possibly others) only renders black window

### ISSUE THREAD

**Issue by ianbeyst** [michaelforney/swc#48]
[Minimal working example.](https://github.com/emersion/hello-wayland)

Besides the blank screen, it seems that Firefox runs perfectly fine otherwise. By carefully moving the mouse around and inspecting changes in the title bar, it is obvious that websites are loaded.
Platform: void linux x86_64-musl, tested on velox and the example wm included with swc.

Any idea what causes this?

**Comment by michaelforney** [comment]
I was able to reproduce this issue. I don't think the hello-wayland example is related (it doesn't call wl_surface.damage, so none of the surface is updated).

It looks to be lack of subsurface support (#25). But I'm happy to see that firefox wayland support almost works with swc. This should be good motivation for finally getting subsurfaces implemented.

**Comment by ianbeyst** [comment]
Thanks for taking a look at this.
I double checked and indeed, if I call `wl_surface_damage` the cat shows up on swc. The question that I still have (if you don't mind me asking) is that even without calling `wl_surface_damage`, the cat shows up under weston. Is this some non-standard behaviour of weston that the hello-wayland example (ab)uses, or is it non-standard behaviour of swc? Just trying to make sense of how wayland is supposed to work.

**Comment by michaelforney** [comment]
I'm not sure. The spec says that the initial damaged region is empty ([link](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_surface-request-damage)):

> The initial value for pending damage is empty: no damage. wl_surface.damage adds pending damage: the new pending damage is the union of old pending damage and the given rectangle.

I suppose the compositor could assume some implicit damage when a buffer is initially attached, or resized to a larger size, though I don't think the spec mentions this anywhere. In practice, this is the first client I've run into that doesn't ever report damage for a surface.
