### ISSUE TITLE
Make -jN doesn't work

### ISSUE THREAD

**Issue by marler8997** [michaelforney/swc#52]
Parallel make doesn't work.  The generated wayland protocol files in `libswc` don't exist before they are needed.

**Comment by michaelforney** [comment]
Can you explain in more detail, perhaps with a failing build log? I can't reproduce the issue.

The generated wayland protocol files have explicit dependencies:
https://github.com/michaelforney/swc/blob/master/libswc/local.mk#L72-L76

**Comment by marler8997** [comment]
I can't reproduce it anymore.  I'll close and will reopen if it happens again and I can get a log.
