### ISSUE TITLE
Doesn't even start, more info in Description

### ISSUE THREAD

**Issue by PalanixYT** [michaelforney/swc#67]
So, when i run swc-run velox I get the following message:
`running on /dev/tty2
(WW) Option "-listen" for file descriptors is deprecatedary
Please use "-listenfd" instead.
(WW) Option "-listen" for file descriptors is deprecated
Please use "-listenfd" instead.
glamor: no eglstream capable devices found
(EE) could not connect to wayland server`

**Comment by PalanixYT** [comment]
ok i am so sorry i just noticed, that this is actually the wrong repo,

so sorry

**Comment by PalanixYT** [comment]
So it says `DEBUG :/dev/dri/card0 is the primary GPU
#find_driver: Trying DRM driver 'intel'
Trying DRM driver 'nouveau'
Trying DRM driver 'dumb'
Couldn't find velox.conf`
The rest is the same as before. Is swc not compatible with AMD cards?

**Comment by michaelforney** [comment]
> Couldn't find velox.conf

This is the problem, you need to create `~/.velox.conf`. There is a sample available in the repository called `velox.conf.sample`.

**Comment by PalanixYT** [comment]
is it possible to have it in ~/.config/velox/.velox.conf?

**Comment by PalanixYT** [comment]
The problem is, that there is still no output? I don't even know if there are windows in the background being opened, but i cant see anything. I can switch the tags, if that helps.

**Comment by michaelforney** [comment]
Which application are you trying to launch that is not showing up?

**Comment by PalanixYT** [comment]
Kitty or dmenu-wl_run, why?

**Comment by michaelforney** [comment]
You're going to have to give me more information than that. Do they print any messages to stderr? How about a wayland protocol log (`WAYLAND_DEBUG=1`).

**Comment by PalanixYT** [comment]
ok turns out, dmenu-wl is wlroots specific. Is there any other one you know of, that i can use with swc?

**Comment by michaelforney** [comment]
https://github.com/michaelforney/dmenu
